runtime: python
env: flex
entrypoint: gunicorn -b :$PORT quizapp.wsgi

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

beta_settings:
  cloud_sql_instances: proj1-369720:us-west3:quizinstance

runtime_config:
  python_version: 3.7

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

#env_variables:
#  # This setting is used in settings.py to configure your ALLOWED_HOSTS
#   APPENGINE_URL: https://cclab-362501.uc.r.appspot.com
#
#handlers:
## This configures Google App Engine to serve the files in the app's static
## directory.
#- url: /static
#  static_dir: static/
#
## This handler routes all requests not caught above to your main app. It is
## required when static routes are defined, but can be omitted (along with
## the entire handlers section) when there are no static files defined.
#- url: /.*
#  script: auto